Support Redhat OS family distribution major version 8
ome/ansible-role-selinux-utils pull request #8
Opened 2022-03-28 11:16 UTC by drmatthews

Splits the task according to OS family.

For `Redhat` family major version 7 installs:

```
 - libselinux-python
 - libsemanage-python
 - policycoreutils-python
```

And for major version 8 installs:

```
 - python3-libselinux
 - python3-libsemanage
 - policycoreutils-python-utils
```

2022-03-31 11:30 UTC, sbesson requested changes
Hi @drmatthews,

thanks for opening a PR against this role. As you probably guessed, its usage is currently tailored to CentOS 7 which is our main operating system for deployment but adding support for other OSes makes sense as long as the existing behavior is retained.

The Molecule tests (which I needed to trigger by opening/closing the PR as the action got auto-disabled) have flagged a few lint errors that needs to be fixed. (see inline comments by GitHub Actions).

Additionally, it looks like the `tasks/debian.yml` and `tasks/redhat.yml` share some  common logic to detect whether selinux is enabled. Can this be moved back into the main YML or isolated into its own imported YAML to differentiate it from OS-specific tasks?

Also do you want to add some testing coverage for the new supported OSes? If so, at minimum https://github.com/ome/ansible-role-selinux-utils/blob/master/molecule/default/molecule.yml should be updated to include new platforms.

2023-08-05 09:10 UTC, drmatthews commented
Hi @sbesson - Apologies that this has been negelected for so long! I have made the following changes:

- Remove support for Debian
- Put tasks back into main.yml
- Add molecule scenario for RockyLinux8
- Addressed linting

2023-08-14 11:01 UTC, sbesson commented
Thanks @drmatthews. Although I am still periodically involved in the maintenance of these Ansible roles, I have changed affiliation and I think both the specific changes and generally the platform support decision will need the input from some of the OME maintainers who I added as reviewer.

With CentOS 7 becoming officially EOL in June 2024, note in particular https://www.openmicroscopy.org/2023/07/24/linux-distributions.html which highlights OME's roadmap in terms of platform support. Rocky Linux 9 and Ubuntu 22.04 are the two candidates so overall this effort aligns with some of the ongoing audit of the roles spearheaded by @pwalczysko. To the best of my knowledge, it is still undecided if the aim of these roles is to support both environments or focus on the one primarily used by the OME team.

2023-09-19 09:51 UTC, pwalczysko commented
> I'll wait for a response from the OME team.

@drmatthews Thank you for this and sorry for the belated response. As stated in https://www.openmicroscopy.org/2023/07/24/linux-distributions.html, the two platforms supported by the OME Team will be Rocky Linux 9 and Ubuntu 22.04. If any additional platforms should be considered, we need an institution to take ownership of the maintenance, not a single individual, otherwise the burden to maintain the new platform will fall on the OME Team.

Hope this position, although very strict, makes sense.

Thanks again

Best wishes

Petr

OME Team

2023-09-19 09:56 UTC, pwalczysko requested changes
As explained in the https://github.com/ome/ansible-role-selinux-utils/pull/8#issuecomment-1725182275 - the maintenance of the new platform will not be overtaken - possibly try to add support for Rocky Linux 9 testing instead ?

2025-10-21 14:59 UTC, closed without merging